# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: output.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'output.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0coutput.proto\"I\n\x10PredictionOutput\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07headers\x18\x02 \x03(\t\x12\x12\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x04.Row\"\x15\n\x03Row\x12\x0e\n\x06values\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'output_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIONOUTPUT']._serialized_start=16
  _globals['_PREDICTIONOUTPUT']._serialized_end=89
  _globals['_ROW']._serialized_start=91
  _globals['_ROW']._serialized_end=112
# @@protoc_insertion_point(module_scope)
