# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_history.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor_history.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sensor_history.proto\"\xae\x01\n\nSensorData\x12\x0f\n\x07sensors\x18\x01 \x03(\t\x12%\n\x05\x64\x61tas\x18\x02 \x03(\x0b\x32\x16.SensorData.DataRecord\x1a\'\n\tDataPoint\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x01(\x02\x1a?\n\nDataRecord\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12#\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x15.SensorData.DataPointb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_history_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA']._serialized_start=25
  _globals['_SENSORDATA']._serialized_end=199
  _globals['_SENSORDATA_DATAPOINT']._serialized_start=95
  _globals['_SENSORDATA_DATAPOINT']._serialized_end=134
  _globals['_SENSORDATA_DATARECORD']._serialized_start=136
  _globals['_SENSORDATA_DATARECORD']._serialized_end=199
# @@protoc_insertion_point(module_scope)
